routes/web.php
<?php

use App\Models\Project;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProjectController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index', [
        'projects' => Project::orderByDesc('created_at')->get()
    ]);
});


Route::get('project/{project:slug}', [ProjectController::class, 'show'])->name('projects.show');

Route::prefix('admin')->middleware('auth', 'verified')->group(
    function () {
        Route::get('dashboard', function () {
            return view('dashboard');
        })->name('dashboard');

        Route::post('projects/image/upload', [ProjectController::class, 'upload'])->name('projects.image.upload');

        Route::resource('projects', ProjectController::class)->except([
            'show'
        ]);
    }
);

require __DIR__ . '/auth.php';

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'subtitle',
        'slug',
        'studio',
        'description',
        'skills',
        'image',
        'url',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'id',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['clean_skills'];

    public function getSkillsAttribute($value)
    {
        return collect(explode(', ', $value));
    }

    public function getCleanSkillsAttribute()
    {
        return $this->getRawOriginal('skills');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use App\Http\Requests\{ProjectStoreRequest, ProjectUpdateRequest};

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.projects.index', [
            'projects' => Project::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectStoreRequest $request)
    {
        $project = Project::create($request->validated() + ['slug' => Str::slug($request->title)]);

        alert()->success("{$project->title} project has been created successfully!");
        return redirect()->route('projects.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        return view('frontend.portfolio.show', [
            'project' => $project
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        return view('backend.projects.edit', [
            'project' => $project
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(ProjectUpdateRequest $request, Project $project)
    {
        $project->update($request->validated());

        alert()->success("{$project->title} project has been updated successfully!");
        return redirect()->route('projects.edit', $project->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
    }

    public function upload(Request $request)
    {
        if ($request->hasFile('file')) {
            $image = $request->file('file');
            $filename = $image->getClientOriginalName();
            $image = Image::make($image);
            $image->encode();

            // Storage::disk('cover')->put($filename, $image);
            $image->save(public_path('images/' . $filename));
        }

        // return response()->json([
        //     'url' => Storage::disk('cover')->url($filename),
        //     'filename' => $filename
        // ]);
        return response()->json($filename);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/backend/projects/create.blade.php
@extends('layouts.backend')

@section('title', "Andy Holmes | Web Developer & Designer")

@section('content')
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form class="mt-8" action="{{ route('projects.store') }}" method="post">
                @csrf
                <div class="row">
                    <div class="col-md-12">
                        <div class="mb-3">
                            <label for="title" class="form-label">Title</label>
                            <input type="text" class="form-control" id="title" name="title" value="{{ old('title') }}">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="mb-3">
                            <label for="subtitle" class="form-label">Subtitle</label>
                            <input type="text" class="form-control" id="subtitle" name="subtitle" value="{{ old('subtitle') }}">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="mb-3">
                            <label for="studio" class="form-label">Studio</label>
                            <input type="text" class="form-control" id="studio" name="studio" value="{{ old('studio') }}">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="mb-3">
                            <label for="skills-list" class="form-label">Skills (comma separated)</label>
                            <input type="text" class="form-control" id="skills-list" name="skills" value="{{ old('skills') }}">
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="website-url" class="form-label">URL</label>
                        <input type="text" class="form-control" id="website-url" name="url" value="{{ old('url') }}">
                    </div>
                    <image-upload></image-upload>
                </div>
                <label for="quill_html" class="form-label">Description</label>
                <div id="quill_editor" style="height: 500px"></div>
                <input type="hidden" id="quill_html" value="" name="description" value="{{ old('description') }}"></input>
                <input type="hidden" name="image" value="" id="imageFilename">
                <button type="submit" class="btn btn-info">Save</button>
            </form>
        </div>
    </div>
</div>
@endsection

@section('footerScripts')
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
<script>
    var quill = new Quill('#quill_editor', {
        theme: 'snow'
    });
    quill.on('text-change', function(delta, oldDelta, source) {
        document.getElementById("quill_html").value = quill.root.innerHTML;
    });
    // quill.setContents("<p>123</p>");
    quill.root.innerHTML = "{!! old('description') !!}";
</script>
@endsection

resources/views/backend/projects/edit.blade.php
@extends('layouts.backend')

@section('title', "Andy Holmes | Web Developer & Designer")

@section('content')
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form class="mt-8" action="{{ route('projects.update', $project->id) }}" method="post">
                @csrf
                @method('put')
                <div class="row">
                    <div class="col-md-12">
                        <div class="mb-3">
                            <label for="title" class="form-label">Title</label>
                            <input type="text" class="form-control" id="title" name="title" value="{{ old('title') ?? $project->title }}">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="mb-3">
                            <label for="subtitle" class="form-label">Subtitle</label>
                            <input type="text" class="form-control" id="subtitle" name="subtitle" value="{{ old('subtitle') ?? $project->subtitle }}">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="mb-3">
                            <label for="studio" class="form-label">Studio</label>
                            <input type="text" class="form-control" id="studio" name="studio" value="{{ old('studio') ?? $project->studio }}">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="mb-3">
                            <label for="skills-list" class="form-label">Skills (comma separated)</label>
                            <input type="text" class="form-control" id="skills-list" name="skills" value="{{ old('skills') ?? $project->clean_skills }}">
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="website-url" class="form-label">URL</label>
                        <input type="text" class="form-control" id="website-url" name="url" value="{{ old('url') ?? $project->url }}">
                    </div>
                    <image-upload></image-upload>
                </div>
                <label for="quill_html" class="form-label">Description</label>
                <div id="quill_editor" style="height: 500px"></div>
                <input type="hidden" id="quill_html" value="" name="description" value="{{ old('description') ?? $project->description }}"></input>
                <input type="hidden" name="image" value="{{ old('image') ?? $project->image }}" id="imageFilename">
                <button type="submit" class="btn btn-info">Save</button>
            </form>
        </div>
    </div>
</div>
@endsection

@section('footerScripts')
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
<script>
    var quill = new Quill('#quill_editor', {
        theme: 'snow'
    });
    quill.on('text-change', function(delta, oldDelta, source) {
        document.getElementById("quill_html").value = quill.root.innerHTML;
    });
    // quill.setContents("<p>123</p>");
    quill.root.innerHTML = "{!! old('description') ?? $project->description !!}";
</script>
@endsection

resources/views/backend/projects/index.blade.php
@extends('layouts.backend')

@section('title', "Andy Holmes | Web Developer & Designer")

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Subtitle</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($projects as $project)
                    <tr>
                        <th scope="row">{{ $project->id }}</th>
                        <td>{{ $project->title }}</td>
                        <td>{{ $project->subtitle }}</td>
                        <td>
                            <a href="{{ route('projects.edit', $project->id) }}">Edit</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('projects.create') }}">Create New Project</a>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard.blade.php
@extends('layouts.backend')

@section('title', "Andy Holmes | Web Developer & Designer")

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                Dashboard View
            </div>
        </div>
    </div>
@endsection

resources/views/frontend/index.blade.php
@extends('layouts.app')

@section('title', "Andy Holmes | Web Developer & Designer")

@section('content')
<div id="intro" class="container">
    <div class="row align-items-center justify-content-center">
        <div class="col-xl-8">
            <div class="intro-heading text-center">
                <div class="intro-heading__title">
                    <span class="block"></span>
                    <h1>Hey, I'm Andy.</h1>
                </div>
                <div class="intro-heading__role">
                    <span class="block"></span>
                    <p>A full stack developer (and occasional designer) from Kent.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="profile">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="profile-inner d-flex flex-column flex-column-reverse flex-lg-row align-items-center align-items-lg-start align-items-xl-end align-items-xxl-center justify-content-center">
                    <img class="profile-inner__image" src="{{ asset('images/Andy-Holmes-Headshot.jpg') }}" alt="Headshot image of Andy">
                    <div class="profile-inner__text">
                        <p>
                            I built my first website at the age of 11 using a website builder called Homestead. I quickly progressed into learning HTML & CSS when I was around 13 and then started learning PHP & MySQL at 16 years old.
                        </p>
                        <p>
                            I have a passion for learning and have taught myself everything I know. On top of web development & design, I’m also a <a rel="noopener" target="_blank" href="https://www.instagram.com/andyjh07/">Photographer</a> and a bit of a <span class="informative">Linguaphile<span class="tooltiptext">A <em>linguaphile</em> is a person who loves language and words.</span></span>; learning a variety of different languages on <a rel="noopener" target="_blank" href="https://www.duolingo.com/profile/andyjh07">Duolingo</a>. I’m always looking to better myself in every aspect and have no problem throwing myself in at the deep end if required.
                        </p>
                        <p>
                            My previous colleagues have described me as a real hybrid or “Unicorn developer” due to my interest & experience in design and in various parts of a business’ lifecycle/processes. Code will always be what makes me tick though, I absolutely love building things and coming up with clever solutions to problems.
                        </p>
                        <p>
                            I pride myself on being a super friendly and approachable person, a real team-player who has no problem getting involved in discussions or meetings. I have over <strong>8 years professional experience</strong> in a variety of project types and can slot into most roles quickly.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="text-center text-lg-start">Portfolio.</h2>
            </div>
        </div>
        <div class="row">
            @forelse($projects as $project)
            <div class="col-md-6 col-lg-4">
                <div class="portfolio-item">
                    <a href="{{ route('projects.show', $project->slug) }}"><img src="{{ asset("images/{$project->image}") }}" alt="Description of image" class="portfolio-item__image"></a>
                    <div class="portfolio-item__content">
                        <h3><a href="{{ route('projects.show', $project->slug) }}">{{ $project->title }}</a></h3>
                        <p>Studio: {{ $project->studio }}</p>
                        <ul class="tags d-flex align-items-center justify-content-start flex-wrap">
                            @foreach($project->skills->take(4) as $skill)
                            <li>{{ $skill }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
            @empty
            <div class="col-12 text-center">
                <p>I'm working on adding some projects into my portfolio, please bear with me!</p>
            </div>
            @endforelse
        </div>
        <div class="row">
            <div class="col-md-12">
                <p class="text-center">As this is a new portfolio, I've added {{ $projects->count() }} out of 15 projects so far. Please bear with me whilst I finish populating my site.</p>
            </div>
        </div>
    </div>
</div>
<div id="skills">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="text-center text-lg-start">Skills.</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <ul class="skills-list d-flex flex-wrap justify-content-center justify-content-lg-start align-items-center flex-column flex-md-row">
                    <li>Photoshop</li>
                    <li>Sketch</li>
                    <li>HTML</li>
                    <li>CSS/SCSS</li>
                    <li>JavaScript</li>
                    <li>jQuery</li>
                    <li>Vue.js 2+</li>
                    <li>AJAX</li>
                    <li>PHP</li>
                    <li>Laravel v5.1+</li>
                    <li>Accessibility</li>
                    <li>Bootstrap v3+</li>
                    <li>Tailwind CSS</li>
                    <li>MySQL</li>
                    <li>API Experience</li>
                    <li>Version Control</li>
                    <li>cPanel Management</li>
                    <li>WordPress ACF</li>
                    <li>WordPress Custom Themes</li>
                    <li>ExpressionEngine v2+</li>
                    <li>Project Management</li>
                    <li>Deploy HQ</li>
                </ul>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/frontend/portfolio/show.blade.php
@extends('layouts.app')

@section('title', "Andy Holmes | Web Developer & Designer")

@section('content')
    <div id="intro" class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-xl-12">
                <div class="intro-heading text-center">
                    <div class="intro-heading__title">
                        <span class="block"></span>
                        <h1>{{ $project->title }}</h1>
                    </div>
                    <div class="intro-heading__role">
                        <span class="block"></span>
                        <p>{{ $project->subtitle }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="profile">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="profile-inner">
                        <img class="w-100" src="{{ asset("images/{$project->image}") }}" alt="Preview image of the {{ $project->name }} project">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="url">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    Visit Website: <a target="_blank" href="{{ $project->url }}">{{ $project->url }}</a>
                </div>
            </div>
        </div>
    </div>
    <div id="project">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="text-center text-lg-start">The Project.</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center text-lg-start">
                    {!! $project->description !!}
                </div>
            </div>
        </div>
    </div>
    <div id="skills">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="text-center text-lg-start">Skills Used.</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <ul class="skills-list d-flex flex-wrap justify-content-center justify-content-lg-start align-items-center flex-column flex-lg-row">
                        @foreach($project->skills as $skill)
                        <li>{{ $skill }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title', 'Andy Holmes | Web Developer & Designer')</title>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <!-- <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script> -->
    <script defer data-domain="andyholmes.me" src="https://plausible.io/js/plausible.outbound-links.js"></script>
</head>

<body class="">
    @include('sweetalert::alert')
    <header>
        <div class="container">
            <div class="row flex-column flex-column-reverse flex-md-row justify-content-between align-items-center">
                <div class="col-12 col-md-6 col-lg-5 col-xl-4 col-xxl-4">
                    <div class="nav-items d-flex justify-content-between align-items-center">
                        <a class="nav-items__item" href="{{ config('app.url') }}#intro">Intro</a>
                        <a class="nav-items__item" href="{{ config('app.url') }}#portfolio">Portfolio</a>
                        <a class="nav-items__item" href="{{ config('app.url') }}#skills">Skills</a>
                        <a class="nav-items__item" href="#contact">Contact</a>
                    </div>
                </div>
                <div class="mb-3 mb-md-0 col-6 col-md-4 col-lg-3 col-xl-2">
                    <div class="social-icons d-flex justify-content-between align-items-center">
                        <div class="social-icons__icon d-flex align-items-center justify-content-center">
                            <a rel="noopener" target="_blank" href="https://dribbble.com/andyjh07"><i class="fab fa-dribbble"></i></a>
                        </div>
                        <div class="social-icons__icon d-flex align-items-center justify-content-center">
                            <a rel="noopener" target="_blank" href="https://instagram.com/andyjh07"><i class="fab fa-instagram"></i></a>
                        </div>
                        <div class="social-icons__icon d-flex align-items-center justify-content-center">
                            <a rel="noopener" target="_blank" href="https://unsplash.com/@andyjh07"><i class="fab fa-unsplash"></i></a>
                        </div>
                        <div class="social-icons__icon d-flex align-items-center justify-content-center">
                            <a rel="noopener" target="_blank" href="https://linkedin.com/in/andyholmes7"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <main role="main">
        <div id="app">
            @yield('content')
            <div id="contact">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h2 class="text-center text-lg-start">Contact Me.</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 text-center text-lg-start">
                            <p class="contact__text">If you'd like to speak to me about a project you've got in mind or a job role
                                you think I'd be a good fit for, please feel free to email me at <a href="mailto:info@andyholmes.me?subject=Website%20Enquiry">info@andyholmes.me</a> and I'll get
                                back to you ASAP!</p>
                            <p class="contact__text">You may also be interested in viewing my CV, so please feel free to <a aria-label="Click to view Andy's CV PDF" target="_blank" href="{{ asset('files/Andy-Holmes-CV-2021.pdf')}}">view
                                    it</a> or <a download aria-label="Click to download Andy's CV PDF" href="{{ asset('files/Andy-Holmes-CV-2021.pdf')}}">download it (PDF File)</a>. I can provide
                                multiple references upon request.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <script src="{{ asset('js/app.js') }}"></script>
    <footer>
        <div class="container">
            <div class="col-md-12 text-center">
                <p class="love d-flex align-items-center justify-content-center">Made with <i class="fas fa-heart fa-gradient"></i> in Chatham, Kent, UK.</p>
            </div>
        </div>
    </footer>
</body>

</html>

resources/views/layouts/backend.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title', 'Andy Holmes | Web Developer & Designer')</title>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
</head>

<body class="">
    @include('sweetalert::alert')
    <header>
        <div class="container">
            <div class="row flex-column flex-column-reverse flex-md-row justify-content-between align-items-center">
                <div class="col-10 col-md-6 col-lg-5 col-xl-4 col-xxl-2">
                    <div class="nav-items d-flex justify-content-between align-items-center">
                        <a class="nav-items__item" href="{{ route('dashboard') }}">Dashboard</a>
                        <a class="nav-items__item" href="{{ route('projects.index') }}">Projects</a>
                    </div>
                </div>
                <div class="mb-3 mb-md-0 col-4 col-lg-3 col-xl-3 text-end">
                    Welcome back, {{ auth()->user()->name }}!
                </div>
            </div>
        </div>
    </header>
    <main role="main">
        <div id="app">
            @yield('content')
        </div>
    </main>
    <script src="{{ asset('js/app.js') }}"></script>
    @yield('footerScripts')
    <footer>
        <div class="container">
            <div class="col-md-12 text-center">
                <p class="love d-flex align-items-center justify-content-center">Made with <i class="fas fa-heart fa-gradient"></i> in Chatham, Kent, UK.</p>
            </div>
        </div>
    </footer>
</body>

</html>

resources/views/layouts/guest.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title', 'Andy Holmes | Web Developer & Designer')</title>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <!-- <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script> -->
    <script defer data-domain="andyholmes.me" src="https://plausible.io/js/plausible.outbound-links.js"></script>
</head>

<body class="">
    <main role="main">
        {{ $slot }}
    </main>
    <script src="{{ asset('js/app.js') }}"></script>
</body>

</html>

resources/views/layouts/navigation.blade.php
Nav